import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { NavigationBar } from "./components/navbar";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Golf Friend Inventory ERP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <head>
        {/* Standard meta tags - ensuring no extra whitespace between tags */}
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>비품 관리 시스템</title>
        <meta name="description" content="비품 관리 및 추적 시스템" />
        {/* Add any other head elements like favicons here, ensuring no leading/trailing whitespace on new lines if they were multi-line */}
      </head>
      <body className={`${inter.variable} font-sans antialiased bg-gray-100`}>
        <NavigationBar /> {/* Add the navigation bar here */}
        <main>{children}</main>
        {/* You could add a footer here if needed */}
      </body>
    </html>
  );
}
